name: Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  DEPS_DIR: /home/runner/work/EchoConnect/dependencies

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ${{ env.DEPS_DIR }}
        key: ${{ runner.os }}-dependencies

    - name: Install QT
      uses: jurplel/install-qt-action@v2
      with:
        dir: ${{ env.DEPS_DIR }}
        version: 5.12.7
        cached: ${{ steps.cache-deps.outputs.cache-hit }}

    - name: Install PulseAudio, Doxygen
      run: sudo apt-get install libpulse-dev clang-tidy-9

    - name: Check code formatting with clang-format
      uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: './libecho ./DemoApp'
        exclude: './libecho/external'
        extensions: 'h,cpp,cc'
        clangFormatVersion: 9

    - name: Create build folder
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Check with clang-tidy
      shell: bash
      run: ${{ github.workspace }}/tools/clang-tidy.sh
