name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  DEPS_DIR: ${{ github.workspace }}/../dependencies

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ${{ env.DEPS_DIR }}
        key: ${{ runner.os }}-dependencies

    - name: Install QT
      uses: jurplel/install-qt-action@v2
      with:
        dir: ${{ env.DEPS_DIR }}
        version: 5.12.7
        cached: ${{ steps.cache-deps.outputs.cache-hit }}

    - name: Create build folder
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Copy GTest DLL to tests folder (temporary workaround, hopefully)
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: cp D:/a/EchoConnect/EchoConnect/build/bin/Debug/gtestd.dll ./libecho/tests/Debug/ && env

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      shell: powershell
      run: ls ./libecho/tests/Debug/ && ctest -C Debug -VV --output-on-failure
      #run: ls ./libecho/tests/Debug/ && ./libecho/tests/Debug/libecho_test.exe
